#!/bin/sh

# build docs
tools/build_docs

# change branch
git checkout gh-pages

# prepare static site
rsync -a --delete --exclude=.gitignore --exclude=.git doc/html/ .
touch .nojekyll
echo "eho.mirantis.com" > CNAME

# disable hools
mv .git/hooks/pre-commit .git/hooks/_pre-commit

git add -A

git commit -am "generated: `date`"

git push origin gh-pages

# enable hools                                                                                                         
mv .git/hooks/_pre-commit .git/hooks/pre-commit
